CREATE SCHEMA `baisc` DEFAULT CHARACTER SET utf8 ;
/*交易订单备份表*/
DROP TABLE IF EXISTS `JDP_TB_TRADE`;
CREATE TABLE `JDP_TB_TRADE` (
`ID` INT NOT NULL COMMENT 'ID' AUTO_INCREMENT,
`TID` VARCHAR(100) NOT NULL COMMENT '交易订单ID' ,
`STATUS` VARCHAR(100) NOT NULL COMMENT '交易状态',
`TYPE` VARCHAR(100) NULL COMMENT '交易类型',
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`BUYER_NICK` VARCHAR(100) NULL COMMENT '买家昵称',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`JDP_CREATED` TIMESTAMP NULL COMMENT '数据推送的创建时间',
`JDP_MODIFIED` TIMESTAMP NULL COMMENT '数据推送的修改时间',
`JDP_HASHCODE` VARCHAR(300) NULL COMMENT 'JDP用来做数据校验的字段',
`JDP_RESPONSE` TEXT NULL COMMENT 'API返回的整个JSON字符串',
`BATCH_NO` INT NULL COMMENT '更新批次',
  PRIMARY KEY (`ID`)
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;

/*交易退款备份表*/
DROP TABLE IF EXISTS `JDP_TB_REFUND`;
CREATE TABLE `JDP_TB_REFUND` (
`ID` INT NOT NULL COMMENT 'ID' AUTO_INCREMENT,
`REFUND_ID` VARCHAR(100) NOT NULL COMMENT '交易退款单ID' ,
`OID` VARCHAR(100) NOT NULL COMMENT '交易订单子ID' ,
`TID` VARCHAR(100) NOT NULL COMMENT '交易订单ID' ,
`STATUS` VARCHAR(100) NOT NULL COMMENT '交易状态',
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`BUYER_NICK` VARCHAR(100) NULL COMMENT '买家昵称',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`JDP_CREATED` TIMESTAMP NULL COMMENT '数据推送的创建时间',
`JDP_MODIFIED` TIMESTAMP NULL COMMENT '数据推送的修改时间',
`JDP_HASHCODE` VARCHAR(300) NULL COMMENT 'JDP用来做数据校验的字段',
`JDP_RESPONSE` TEXT NULL COMMENT 'API返回的整个JSON字符串',
`BATCH_NO` INT NULL COMMENT '更新批次',
  PRIMARY KEY (`ID`)
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;

/*聚石塔订单原始表解析*/
DROP TABLE IF EXISTS `JST_TRADE`;
CREATE TABLE `JST_TRADE` (
`JST_TRADE_SYS_ID` INT NOT NULL COMMENT '主键' AUTO_INCREMENT,
`ADJUST_FEE` DECIMAL(10,2) NULL COMMENT '卖家手工调整金额',
`ALIPAY_ID` VARCHAR(200)  NULL COMMENT '买家的支付宝ID号，在UIC中有记录，买家支付宝的唯一标示，不因为买家更换EMAIL账号而改变',
`ALIPAY_NO` VARCHAR(200)  NULL COMMENT '支付宝交易号',
`ALIPAY_POINT` INT  NULL COMMENT '付款时使用的支付宝积分的额度,单位分，比如返回1，则为1分钱',
`AVAILABLE_CONFIRM_FEE` DECIMAL(10,2) NULL COMMENT '交易中剩余的确认收货金额（这个金额会随着子订单确认收货而不断减少，交易成功后会变为零）',
`BUYER_ALIPAY_NO` VARCHAR(200)  NULL COMMENT '买家支付宝账号',
`BUYER_AREA` VARCHAR(200)  NULL COMMENT '买家下单的地区',
`BUYER_COD_FEE` DECIMAL(10,2) NULL COMMENT '买家货到付款服务费',
`BUYER_EMAIL` VARCHAR(200)  NULL COMMENT '买家邮件地址',
`BUYER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`BUYER_OBTAIN_POINT_FEE` INT NULL COMMENT '买家获得积分,返点的积分',
`BUYER_RATE` VARCHAR(10) NULL COMMENT '买家是否已评价可选值:TRUE(已评价),FALSE(未评价)。如买家只评价未打分，此字段仍返回FALSE',
`COD_FEE` DECIMAL(10,2) NULL COMMENT '货到付款服务费',
`COD_STATUS` VARCHAR(200)  NULL COMMENT '货到付款物流状态。初始状态 NEW_CREATED,接单成功 ACCEPTED_BY_COMPANY,接单失败 REJECTED_BY_COMPANY,接单超时 RECIEVE_TIMEOUT,揽收成功 TAKEN_IN_SUCCESS,揽收失败 TAKEN_IN_FAILED,揽收超时 TAKEN_TIMEOUT,签收成功 SIGN_IN,签收失败 REJECTED_BY_OTHER_SIDE,订单等待发送给物流公司 WAITING_TO_BE_SENT,用户取消物流订单 CANCELED',
`COMMISSION_FEE` DECIMAL(10,2) NULL COMMENT '交易佣金',
`CONSIGN_TIME` TIMESTAMP NULL COMMENT '卖家发货时间',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`CREDIT_CARD_FEE` DECIMAL(10,2) NULL COMMENT '使用信用卡支付金额数',
`DISCOUNT_FEE` DECIMAL(10,2) NULL COMMENT '系统优惠金额',
`END_TIME` TIMESTAMP NULL COMMENT '交易结束时间',
`HAS_POST_FEE` VARCHAR(10) NULL COMMENT '是否包含邮费，与AVAILABLE_CONFIRM_FEE同时使用',
`INVOICE_NAME` VARCHAR(200) NULL COMMENT '发票抬头',
`IS_3D` VARCHAR(10)  NULL COMMENT '是否3D交易',
`IS_BRAND_SALE` VARCHAR(10)  NULL COMMENT '表示是否是品牌特卖',
`IS_DAIXIAO` VARCHAR(10) NULL COMMENT '表示订单交易是否含有对应的代销采购单BOOLEAN',
`IS_FORCE_WLB` VARCHAR(10)  NULL COMMENT '订单是否强制使用物流宝发货，当此字段与IS_BRAND_SALE均为TRUE时，订单强制物流宝发货',
`IS_LGTYPE` VARCHAR(10)  NULL COMMENT '是否保障速递，如果为TRUE，则为保障速递订单，使用线下联系发货接口发货，如果未FALSE，则该订单非保障速递，根据卖家设置的订单流转规则可使用物流宝或者常规物流发货',
`IS_PART_CONSIGN` VARCHAR(10)  NULL COMMENT '是否是多次发货的订单如果卖家对订单进行多次发货BOOLEAN',
`IS_WT` VARCHAR(10)  NULL COMMENT '表示订单交易是否网厅订单BOOLEAN',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`NUM` INT NULL COMMENT '商品购买数量',
`NUM_IID` VARCHAR(200) NULL COMMENT '商品数字编号',
`PAY_TIME` TIMESTAMP NULL COMMENT '付款时间',
`PAYMENT` DECIMAL(10,2)  NULL COMMENT '实付金额',
`PCC_AF` INT NULL COMMENT '天猫点券卡实付款金额,单位分',
`PIC_PATH` VARCHAR(200)  NULL COMMENT '商品图片绝对路径',
`POINT_FEE` DECIMAL(10,2) NULL COMMENT '买家使用积分,下单时生成，且一直不变',
`POST_FEE` DECIMAL(10,2) NULL COMMENT '邮费',
`PRICE` DECIMAL(10,2) NULL COMMENT '	商品价格',
`REAL_POINT_FEE` INT  NULL COMMENT '买家实际使用积分（扣除部分退款使用的积分），交易完成后生成（交易成功或关闭），交易未完成时该字段值为0',
`RECEIVED_PAYMENT` DECIMAL(10,2) NULL COMMENT '卖家实际收到的支付宝打款金额（由于子订单可以部分确认收货，这个金额会随着子订单的确认收货而不断增加，交易成功后等于买家实付款减去退款金额）',
`RECEIVER_ADDRESS` VARCHAR(200)  NULL COMMENT '收货人的详细地址',
`RECEIVER_CITY` VARCHAR(200) NULL COMMENT '收货人的所在城市',
`RECEIVER_DISTRICT` VARCHAR(200) NULL COMMENT '收货人的所在地区',
`RECEIVER_MOBILE` VARCHAR(200)  NULL COMMENT '收货人的手机号码',
`RECEIVER_NAME` VARCHAR(200)  NULL COMMENT '收货人的姓名',
`RECEIVER_STATE` VARCHAR(200)  NULL COMMENT '收货人的所在省份',
`RECEIVER_ZIP` VARCHAR(200)  NULL COMMENT '收货人的邮编',
`SELLER_ALIPAY_NO` VARCHAR(200)  NULL COMMENT '卖家支付宝账号',
`SELLER_CAN_RATE` VARCHAR(10)  NULL COMMENT '卖家是否可以对订单进行评价BOOLEAN',
`SELLER_COD_FEE`DECIMAL(10,2)  NULL COMMENT '卖家货到付款服务费',
`SELLER_EMAIL` VARCHAR(200)  NULL COMMENT '卖家邮件地址',
`SELLER_FLAG` VARCHAR(200) NULL COMMENT '卖家备注旗帜',
`SELLER_MEMO` VARCHAR(1000) NULL COMMENT '卖家备注',
`SELLER_MOBILE` VARCHAR(200)  NULL COMMENT '卖家手机',
`SELLER_NAME` VARCHAR(200)  NULL COMMENT '卖家姓名',
`SELLER_NICK` VARCHAR(200) NULL COMMENT '卖家昵称',
`SELLER_PHONE` VARCHAR(200)  NULL COMMENT '卖家电话',
`SELLER_RATE` VARCHAR(200)  NULL COMMENT '卖家是否已评价',
`SHIPPING_TYPE` VARCHAR(200) NULL COMMENT '创建交易时的物流方式',
`SNAPSHOT_URL` VARCHAR(200)  NULL COMMENT '交易快照地址',
`STATUS` VARCHAR(200) NULL COMMENT '交易状态',
`STEP_PAID_FEE` DECIMAL(10,2) NULL COMMENT '分阶段付款的已付金额（万人团订单已付金额）',
`STEP_TRADE_STATUS` VARCHAR(200) NULL COMMENT '分阶段付款的订单状态（例如万人团订单等），目前有三返回状态FRONT_NOPAID_FINAL_NOPAID(定金未付尾款未付)，FRONT_PAID_FINAL_NOPAID(定金已付尾款未付)，FRONT_PAID_FINAL_PAID(定金和尾款都付)',
`TID` VARCHAR(200) NULL COMMENT '交易编号',
`TITLE` VARCHAR(200) NULL COMMENT '交易标题，以店铺名作为此标题的值',
`TOTAL_FEE` DECIMAL(10,2) NULL COMMENT '商品金额（商品价格乘以数量的总金额）',
`TRADE_FROM` VARCHAR(200) NULL COMMENT '交易内部来源',
`TYPE` VARCHAR(200) NULL COMMENT '交易类型列表',
/*自添字段*/
`STORE_ID` VARCHAR(100) NULL COMMENT '商店ID',
/*未使用的字段*/
`RECEIVER_PHONE` VARCHAR(200)  NULL COMMENT '收货人的电话号码',
`EST_CON_TIME` TIMESTAMP NULL COMMENT '商家的预计发货时间',
`INVOICE_KIND` VARCHAR(10) NULL COMMENT '发票类型(1电子发票2纸质发票)',
`RECEIVER_COUNTRY` VARCHAR(200) NULL COMMENT '收货人国籍',
`RECEIVER_TOWN` VARCHAR(200) NULL COMMENT '收货人街道地址',
`ORDER_TAX_FEE` DECIMAL(10,2) NULL COMMENT '天猫国际官网直供主订单关税税费',
`BUYER_MESSAGE` VARCHAR(500) NULL COMMENT '买家留言',
`BUYER_MEMO` VARCHAR(500) NULL COMMENT '买家备注',
`BUYER_FLAG` INT NULL COMMENT '买家备注旗帜',
`INVOICE_TYPE` VARCHAR(200) NULL COMMENT '发票类型',
`MARK_DESC` VARCHAR(200) NULL COMMENT '订单出现异常问题的时候，给予用户的描述,没有异常的时候，此值为空',
`SHOP_CODE` VARCHAR(200) NULL COMMENT '线下自提门店编码',
`TIMEOUT_ACTION_TIME` TIMESTAMP NULL COMMENT '超时到期时间',
`PROMOTION` VARCHAR(200) NULL COMMENT '交易促销详细信息',
`ET_SER_TIME` TIMESTAMP NULL COMMENT '天猫汽车服务预约时间',
`ET_SHOP_NAME` VARCHAR(200) NULL COMMENT '电子凭证预约门店地址',
`ET_VERIFIED_SHOP_NAME` VARCHAR(200) NULL COMMENT '电子凭证核销门店地址',
`ET_PLATE_NUMBER` VARCHAR(200) NULL COMMENT '车牌号码',
`PAID_COUPON_FEE` DECIMAL(10,2) NULL COMMENT '满返红包的金额；如果没有满返红包，则值为 0.00',
`SID` VARCHAR(200) NULL COMMENT '物流运单号',
`BUYER_IP` VARCHAR(200) NULL COMMENT '买家下单的IP信息',
`HAS_YFX` VARCHAR(200) NULL COMMENT '订单中是否包含运费险订单，如果包含运费险订单返回TRUE，不包含运费险订单，返回FALSE',
`YFX_FEE` DECIMAL(10,2) NULL COMMENT '订单的运费险，单位为元',
`YFX_ID` VARCHAR(200) NULL COMMENT '运费险支付号',
`YFX_TYPE` VARCHAR(200) NULL COMMENT '运费险类型',
`ETICKET_EXT` VARCHAR(200) NULL COMMENT '电子凭证的垂直信息',
`SEND_TIME` TIMESTAMP NULL COMMENT '订单将在此时间前发出，主要用于预售订单',
`EXPRESS_AGENCY_FEE` DECIMAL(10,2) NULL COMMENT '快递代收款',
`CAN_RATE` VARCHAR(10) NULL COMMENT '买家可以通过此字段查询是否当前交易可以评论',
`ACOOKIE_ID` VARCHAR(200) NULL COMMENT 'ACOOKIE订单唯一ID',
`TRADE_MEMO` VARCHAR(200) NULL COMMENT '交易备注',
`TRADE_SOURCE` VARCHAR(200) NULL COMMENT '交易外部来源：OWNSHOP(商家官网)',
`ARRIVE_INTERVAL` INT NULL COMMENT '物流到货时效，单位天',
`ARRIVE_CUT_TIME` VARCHAR(200) NULL COMMENT '物流到货时效截单时间，格式 HH:MM',
`CONSIGN_INTERVAL` INT NULL COMMENT '物流发货时效，单位小时',
`O2O` VARCHAR(200) NULL COMMENT '导购宝=CRM',
`O2O_GUIDE_ID` VARCHAR(200) NULL COMMENT '导购员ID',
`O2O_SHOP_ID` VARCHAR(200) NULL COMMENT '导购员门店ID',
`O2O_GUIDE_NAME` VARCHAR(200) NULL COMMENT '导购员名称',
`O2O_SHOP_NAME` VARCHAR(200) NULL COMMENT '导购门店名称',
`O2O_DELIVERY` VARCHAR(200) NULL COMMENT '导购宝提货方式，INSHOP：店内提货，ONLINE：线上发货',
`ZERO_PURCHASE` VARCHAR(10) NULL COMMENT '在返回的TRADE对象上专门增加一个字段ZERO_PURCHASE来区分，这个为TRUE的就是0元购机预授权交易BOOLEAN',
`O2O_OUT_TRADE_ID` VARCHAR(200) NULL COMMENT '外部订单号',
`HK_EN_NAME` VARCHAR(200) NULL COMMENT '拼音名',
`HK_FLIGHT_NO` VARCHAR(200) NULL COMMENT '航班号',
`HK_CHINA_NAME` VARCHAR(200) NULL COMMENT '中文名',
`HK_CARD_CODE` VARCHAR(200) NULL COMMENT '证件号码',
`HK_CARD_TYPE` VARCHAR(200) NULL COMMENT '证件类型001代表港澳通行证类型、002代表入台证003代表护照',
`HK_FLIGHT_DATE` VARCHAR(200) NULL COMMENT '航班飞行时间',
`HK_GENDER` VARCHAR(200) NULL COMMENT '性别M: 男性，F: 女性',
`HK_BIRTHDAY` VARCHAR(200) NULL COMMENT '出生日期',
`HK_PICKUP` VARCHAR(200) NULL COMMENT '提货地点',
`HK_PICKUP_ID` VARCHAR(200) NULL COMMENT '提货地点ID',
`ETICKET_SERVICE_ADDR` VARCHAR(200) NULL COMMENT '天猫电子凭证家装',
`IS_SH_SHIP` VARCHAR(10) NULL COMMENT '是否屏蔽发货BOOLEAN',
`O2O_SNATCH_STATUS` VARCHAR(10) NULL COMMENT '抢单状态 0,未处理待分发;1,抢单中;2,已抢单;3,已发货;-1,超时;-2,处理异常;-3,匹配失败;-4,取消抢单;-5,退款取消;-9,逻辑删除',
`MARKET` VARCHAR(200) NULL COMMENT '垂直市场',
`ET_TYPE` VARCHAR(200) NULL COMMENT '电子凭证扫码购-扫码支付订单TYPE',
`ET_SHOP_ID` VARCHAR(200) NULL COMMENT '扫码购关联门店',
`OBS` VARCHAR(200) NULL COMMENT '门店预约自提订单标',
  PRIMARY KEY (`JST_TRADE_SYS_ID`)
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;

/*聚石塔订单商品原始表*/
DROP TABLE IF EXISTS `JST_ORDER`;
CREATE TABLE `JST_ORDER` (
`JST_ORDER_SYS_ID` INT NOT NULL COMMENT '' AUTO_INCREMENT,
`JST_TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ADJUST_FEE` DOUBLE NULL COMMENT '手工调整金额.格式为:1.01;单位:元;精确到小数点后两位',
`BUYER_RATE` VARCHAR(10) NULL COMMENT '买家是否已评价BOOLEAN',
`CID` VARCHAR(100) NULL COMMENT '交易商品对应的类目ID',
`CONSIGN_TIME` TIMESTAMP NULL COMMENT '子订单发货时间',
`DISCOUNT_FEE` DECIMAL(10,2) NULL COMMENT '子订单级订单优惠金额',
`DIVIDE_ORDER_FEE` DECIMAL(10,2) NULL COMMENT '分摊之后的实付金额',
`END_TIME` TIMESTAMP NULL COMMENT '子订单的交易结束时间',
`INVOICE_NO` VARCHAR(100) NULL COMMENT '子订单所在包裹的运单号',
`IS_OVERSOLD` VARCHAR(10) NULL COMMENT '是否超卖',
`IS_WWW` VARCHAR(10) NULL COMMENT '子订单是否是WWW订单Boolean',
`LOGISTICS_COMPANY` VARCHAR(100) NULL COMMENT '子订单发货的快递公司名称',
`NUM` INT NULL COMMENT '购买数量',
`NUM_IID` VARCHAR(100) NULL COMMENT '商品数字ID',
`OID` VARCHAR(100) NULL COMMENT '子订单编号',
`ORDER_FROM` VARCHAR(100) NULL COMMENT '子订单来源',
`PART_MJZ_DISCOUNT` DECIMAL(10,2) NULL COMMENT '优惠分摊',
`PAYMENT` DECIMAL(10,2) NULL COMMENT '子订单实付金额',
`PIC_PATH` VARCHAR(100) NULL COMMENT '商品图片的绝对路径',
`PRICE` DECIMAL(10,2) NULL COMMENT '商品价格',
`REFUND_ID` VARCHAR(100) NULL COMMENT '最近退款ID',
`REFUND_STATUS` VARCHAR(100) NULL COMMENT '退款状态',
`SELLER_RATE` VARCHAR(10) NULL COMMENT '卖家是否已评价BOOLEAN',
`SELLER_TYPE` VARCHAR(10) NULL COMMENT '卖家类型，可选值为：B（商城商家），C（普通卖家）',
`SHIPPING_TYPE` VARCHAR(100) NULL COMMENT '子订单的运送方式',
`SKU_ID` VARCHAR(100) NULL COMMENT '商品的最小库存单位SKU的ID',
`SKU_PROPERTIES_NAME` VARCHAR(100) NULL COMMENT 'SKU的值,如：机身颜色:黑色;手机套餐:官方标配',
`SNAPSHOT_URL` VARCHAR(100) NULL COMMENT '订单快照URL',
`STATUS` VARCHAR(100) NULL COMMENT '订单状态',
`STORE_CODE` VARCHAR(100) NULL COMMENT '发货的仓库编码',
`TITLE` VARCHAR(100) NULL COMMENT '商品标题',
`TOTAL_FEE` DECIMAL(10,2) NULL COMMENT '应付金额',
/*未使用的字段*/
`ITEM_MEAL_NAME` VARCHAR(50) NULL COMMENT '套餐的值',
`OUTER_IID` VARCHAR(100) NULL COMMENT '商家外部编码',
`TIMEOUT_ACTION_TIME` TIMESTAMP NULL COMMENT '订单超时到期时间',
`SUB_ORDER_TAX_FEE` VARCHAR(100) NULL COMMENT '天猫国际官网直供子订单关税税费',
`SUB_ORDER_TAX_RATE` VARCHAR(100) NULL COMMENT '天猫国际官网直供子订单关税税率',
`ITEM_MEAL_ID` VARCHAR(100) NULL COMMENT '套餐ID',
`OUTER_SKU_ID`  VARCHAR(100) NULL COMMENT '外部网店自己定义的SKU编号',
`IS_SERVICE_ORDER` VARCHAR(10) NULL COMMENT '是否是服务订单Boolean',
`BIND_OID` VARCHAR(100) NULL COMMENT '捆绑的子订单号',
`IS_DAIXIAO` VARCHAR(10) NULL COMMENT '表示订单交易是否含有对应的代销采购单BOOLEAN',
`TICKET_OUTER_ID` VARCHAR(100) NULL COMMENT '对应门票有效期的外部ID',
`TICKET_EXPDATE_KEY` VARCHAR(100) NULL COMMENT '门票有效期的KEY',
`TMSER_SPU_CODE` VARCHAR(100) NULL COMMENT '支持家装类物流的类型',
`MATNR` VARCHAR(100) NULL COMMENT 'SKU CODE',
`ITEM_MEMO` VARCHAR(100) NULL COMMENT '商品备注',
`ET_SER_TIME` TIMESTAMP NULL COMMENT '天猫汽车服务预约时间',
`ET_SHOP_NAME` VARCHAR(100) NULL COMMENT '电子凭证预约门店地址',
`ET_VERIFIED_SHOP_NAME` VARCHAR(100) NULL COMMENT '电子凭证核销门店地址',
`ET_PLATE_NUMBER` VARCHAR(100) NULL COMMENT '车牌号码',
`ESTIMATE_CON_TIME` VARCHAR(100) NULL COMMENT '子订单预计发货时间',
`BIND_OIDS` VARCHAR(200) NULL COMMENT 'BIND_OID字段的升级，支持返回绑定的多个子订单，多个子订单以半角逗号分隔',
`ZHENGJI_STATUS` VARCHAR(10) NULL COMMENT '征集预售订单征集状态：1（征集中），2（征集成功），3（征集失败）',
PRIMARY KEY (`JST_ORDER_SYS_ID`),
FOREIGN KEY (`JST_TRADE_SYS_ID`) REFERENCES JST_TRADE(`JST_TRADE_SYS_ID`) ON DELETE CASCADE
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;

/*聚石塔订单促销原始表*/
DROP TABLE IF EXISTS `JST_PROMOTION_DETAIL`;
CREATE TABLE `JST_PROMOTION_DETAIL` (
  `JST_PROMOTION_DETAIL_SYS_ID` INT NOT NULL COMMENT '交易的注定单或子订单号' AUTO_INCREMENT,
  `JST_TRADE_SYS_ID` INT NOT NULL COMMENT '',
  `ID` VARCHAR(100) NULL COMMENT '',
  `PROMOTION_NAME` VARCHAR(100) NULL COMMENT '优惠信息的名称',
  `DISCOUNT_FEE` DECIMAL(10,2) NULL COMMENT '优惠金额',
  `PROMOTION_DESC` VARCHAR(100) NULL COMMENT '优惠活动的描述',
  `PROMOTION_ID` VARCHAR(100) NULL COMMENT '优惠ID',
  `PROMOTION_TYPE` VARCHAR(100) NULL COMMENT '优惠券类型',
  PRIMARY KEY (`JST_PROMOTION_DETAIL_SYS_ID`),
  FOREIGN KEY (`JST_TRADE_SYS_ID`) REFERENCES JST_TRADE(`JST_TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;

/*聚石塔订单原始表解析*/
DROP TABLE IF EXISTS `JST_REFUND`;
CREATE TABLE `JST_REFUND` (
`JST_REFUND_SYS_ID` INT NOT NULL COMMENT '' AUTO_INCREMENT,
`ADVANCE_STATUS` VARCHAR(10) NULL COMMENT '退款先行垫付默认的未申请状态 0;退款先行垫付申请中 1;退款先行垫付，垫付完成 2;退款先行垫付，卖家拒绝收货 3;退款先行垫付，垫付关闭 4;退款先行垫付，垫付分账成功 5;' ,
`ALIPAY_NO` VARCHAR(100) NULL COMMENT '支付宝交易号' ,
`ATTRIBUTE` VARCHAR(1000) NULL COMMENT '退款扩展属性' ,
`BUYER_NICK` VARCHAR(100) NULL COMMENT '买家昵称',
`CREATED` TIMESTAMP NULL COMMENT '退款申请时间',
`CS_STATUS` VARCHAR(10) NULL COMMENT '不需客服介入1;需要客服介入2;客服已经介入3;客服初审完成 4;客服主管复审失败5;客服处理完成6' ,
`DESC` VARCHAR(10) NULL COMMENT '退款说明' ,
`GOOD_STATUS` VARCHAR(100) NULL COMMENT '货物状态' ,
`HAS_GOOD_RETURN` VARCHAR(10) NULL COMMENT '买家是否需要退货BOOLEAN' ,
`MODIFIED` TIMESTAMP NULL COMMENT '更新时间',
`NUM` INT NULL COMMENT '商品购买数量' ,
`NUM_IID` VARCHAR(100) NULL COMMENT '申请退款的商品数字编号' ,
`OID` VARCHAR(100) NULL COMMENT '子订单号。如果是单笔交易OID会等于TID' ,
`OPERATION_CONTRAINT` VARCHAR(100) NULL COMMENT '退款约束' ,
`ORDER_STATUS` VARCHAR(100) NULL COMMENT '退款对应的订单交易状态',
`OUTER_ID` VARCHAR(100) NULL COMMENT '商品外部商家编码' ,
`PAYMENT` DECIMAL(10,2) NULL COMMENT '支付给卖家的金额(交易总金额-退还给买家的金额)' ,
`PRICE` DECIMAL(10,2) NULL COMMENT '商品价格' ,
`REASON` VARCHAR(200) NULL COMMENT '退款原因' ,
`REFUND_FEE` DECIMAL(10,2) NULL COMMENT '退还给买家的金额' ,
`REFUND_ID` VARCHAR(100) NULL COMMENT '退款单号' ,
`REFUND_PHASE` VARCHAR(10) NULL COMMENT '退款阶段，可选值：ONSALE/AFTERSALE' ,
`REFUND_VERSION` VARCHAR(100) NULL COMMENT '退款版本号' ,
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`SKU` VARCHAR(100) NULL COMMENT '商品SKU信息' ,
`STATUS` VARCHAR(100) NULL COMMENT '退款状态',
`TID` VARCHAR(100) NULL COMMENT '淘宝交易单号' ,
`TITLE` VARCHAR(100) NULL COMMENT '商品标题' ,
`TOTAL_FEE` DECIMAL(10,2) NULL COMMENT '交易总金额' ,
`SHIPPING_TYPE` VARCHAR(100) NULL COMMENT '物流方式.可选值:FREE(卖家包邮),POST(平邮),EXPRESS(快递),EMS(EMS).' ,
`SPLIT_TAOBAO_FEE` DECIMAL(10,2) NULL COMMENT '分账给淘宝的钱' ,
`SPLIT_SELLER_FEE` DECIMAL(10,2) NULL COMMENT '分账给卖家的钱' ,
`GOOD_RETURN_TIME` TIMESTAMP NULL COMMENT '退货时间' ,
`COMPANY_NAME` VARCHAR(100) NULL COMMENT '物流公司名称' ,
`SID` VARCHAR(100) NULL COMMENT '退货运单号' ,
`ADDRESS` VARCHAR(200) NULL COMMENT '卖家收货地址' ,
`STORE_ID` VARCHAR(100) NULL COMMENT '商店CODE' ,
`RECORD_CREATE` TIMESTAMP NULL COMMENT '交易创建时间',
  PRIMARY KEY (`JST_REFUND_SYS_ID`)
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;

/*字典表*/
DROP TABLE IF EXISTS `SYS_VALUE`;
CREATE TABLE `SYS_VALUE` (
`SYS_VALUE_ID` INT NOT NULL COMMENT 'ID' AUTO_INCREMENT,
`STATUS` VARCHAR(100) NOT NULL COMMENT '交易状态',
`TYPE` VARCHAR(100) NULL COMMENT '交易类型',
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`BUYER_NICK` VARCHAR(100) NULL COMMENT '买家昵称',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`JDP_CREATED` TIMESTAMP NULL COMMENT '数据推送的创建时间',
`JDP_MODIFIED` TIMESTAMP NULL COMMENT '数据推送的修改时间',
`JDP_HASHCODE` VARCHAR(300) NULL COMMENT 'JDP用来做数据校验的字段',
`JDP_RESPONSE` TEXT NULL COMMENT 'API返回的整个JSON字符串',
`BATCH_NO` INT NULL COMMENT '更新批次',
  PRIMARY KEY (`ID`)
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;





CREATE TABLE `baisc`.`upload_template_history` (
  `id` INT NOT NULL DEFAULT 100 COMMENT '主键ID',
  `template_name` VARCHAR(100) NOT NULL COMMENT '模版名称',
  `template_column` VARCHAR(45) NOT NULL COMMENT '列名称',
  `template_column_index` INT NULL COMMENT '列顺序',
  `create_time` TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `create_op` VARCHAR(45) NOT NULL COMMENT '创建人',
  `must_exists` INT NULL COMMENT '列是否必须存在，0为非必须，1为必须',
  `ignore_column_index` INT NULL COMMENT '是否忽略排序，只看模版中必须存在的列名，0忽略，1为不忽略',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '模版上传历史记录';

/*订单报表配置表*/
CREATE TABLE `baisc`.`tbl_order_report_config` (
  `ID` INT NOT NULL COMMENT '',
  `TITLE_NAME` VARCHAR(200) NULL COMMENT '报表列名',
  `ACTUAL_TABLE_NAME` VARCHAR(200) NULL COMMENT '涉及字段的表名',
  `RULE` VARCHAR(200) NULL COMMENT '取值规则',
  `DESCRIPTION` VARCHAR(200) NULL COMMENT '规则描述信息',
  `CONSTANT_VALUE` VARCHAR(200) NULL COMMENT '固定值',
  `ORDER_INDEX` INT NULL COMMENT '排序方式',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '模版上传历史记录';



