/*聚石塔订单促销原始表*/
DROP TABLE IF EXISTS `JST_PROMOTION_DETAIL`;
CREATE TABLE `JST_PROMOTION_DETAIL` (
  `JST_PROMOTION_DETAIL_SYS_ID` INT NOT NULL COMMENT '交易的注定单或子订单号' AUTO_INCREMENT,
  `JST_TRADE_SYS_ID` INT NOT NULL COMMENT '',
  `ID` VARCHAR(100) NULL COMMENT '',
  `PROMOTION_NAME` VARCHAR(100) NULL COMMENT '优惠信息的名称',
  `DISCOUNT_FEE` DECIMAL(10,2) NULL COMMENT '优惠金额',
  `PROMOTION_DESC` VARCHAR(100) NULL COMMENT '优惠活动的描述',
  `PROMOTION_ID` VARCHAR(100) NULL COMMENT '优惠ID',
  `PROMOTION_TYPE` VARCHAR(100) NULL COMMENT '优惠券类型',
  PRIMARY KEY (`JST_PROMOTION_DETAIL_SYS_ID`),
  FOREIGN KEY (`JST_TRADE_SYS_ID`) REFERENCES JST_TRADE(`JST_TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;