
/*备注解析表*/
DROP TABLE IF EXISTS `JST_TRADE_REMARK`;
CREATE TABLE `JST_TRADE_REMARK` (
`JST_TRADE_REMARK_SYS_ID` INT NOT NULL COMMENT '' AUTO_INCREMENT,
`TID` VARCHAR(200) NOT NULL COMMENT '',
`INVOICE_TITLE` VARCHAR(500) NULL COMMENT '发票抬头',
`RECEIVE_NAME` VARCHAR(100) NULL COMMENT '收件人姓名',
`MOBILE` VARCHAR(100) NULL COMMENT '手机号码',
`PHONE` VARCHAR(100) NULL COMMENT '固定电话',
`RECEIVE_ADDRESS` VARCHAR(500) NULL COMMENT '收获地址',
`RECEIVE_ZIP` VARCHAR(100) NULL COMMENT '邮编',
`QUANTITY` INT NULL COMMENT '商品数量',
`TICKET_NAME` VARCHAR(500) NULL COMMENT '增票名称',
`TICKET_CODE` VARCHAR(500) NULL COMMENT '增票税号',
`TICKET_ADDRESS` VARCHAR(500) NULL COMMENT '增票地址电话',
`TICKET_ACCOUNT` VARCHAR(500) NULL COMMENT '增票名称',
PRIMARY KEY (`JST_TRADE_REMARK_SYS_ID`)
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;


/*备注礼品解析表*/
DROP TABLE IF EXISTS `JST_TRADE_REMARK_PRESENT`;
CREATE TABLE `JST_TRADE_REMARK_PRESENT` (
`PRESENT_SYS_ID` INT NOT NULL COMMENT '' AUTO_INCREMENT,
`JST_TRADE_REMARK_SYS_ID` INT NOT NULL COMMENT '',
`PRESENT_REASON` VARCHAR(200) NULL COMMENT '赠送原因',
`PRESENT_NAME` VARCHAR(100) NULL COMMENT '礼品名称',
`PRESENT_QUANTITY` INT NULL COMMENT '礼品数量',
PRIMARY KEY (`PRESENT_SYS_ID`),
FOREIGN KEY (`JST_TRADE_REMARK_SYS_ID`) REFERENCES JST_TRADE_REMARK(`JST_TRADE_REMARK_SYS_ID`) ON DELETE CASCADE
)
ENGINE = INNODB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = UTF8;